### ISSUE TITLE
Error al declarar variables

### ISSUE THREAD

**Issue by gl3ncal3l** [ericknavarro/InterpreteSencilloWindows#10]
- Al declarar una variable no se realiza ninguna verificación si esta ya existe en la tabla de símbolos. 

- El lenguaje no maneja ámbitos.

**Comment by ericknavarro** [comment]
Colocar un ejemplo de código en el que falle el tema de verificación de variables.
Colocar un ejemplo de código en el que no se manejen correctamente los ámbitos.

**Comment by gl3ncal3l** [comment]
Ejemplo de verificación de variables.
![Sin título](https://user-images.githubusercontent.com/12867424/73043907-d9b19b00-3e2c-11ea-8dd2-1f956689abdc.png)

Ejemplo del manejo de ámbitos.
![Sin título(copia)](https://user-images.githubusercontent.com/12867424/73043905-d9190480-3e2c-11ea-8c6c-6b3a5d257d6f.png)

**Comment by ericknavarro** [comment]
Me parece que ambos casos están relacionados con el mismo problema, es posible declarar una variable más de una vez.

**Comment by ericknavarro** [comment]
Buenas tardes @gl3ncal3l , por favor trabajar en la propuesta. 

Saludos cordiales.
