### ISSUE TITLE
Mejora del Proyecto - Mejora del Tiempo de Respuesta de la Tabla de Símbolos + proposición de entornos

### ISSUE THREAD

**Issue by Puac235** [ericknavarro/InterpreteSencilloWindows#12]
Actualmente, la clase TablaDeSimbolos extiende de una LinkedList, en la cual se guardan las variables compiladas al momento de ejecutar el proyecto.
Como es una LinkedList, al momento de tener muchas variables, esta debe de recorrer toda la lista hasta encontrar la variable solicitada; y esto puede afectar al rendimiento de la aplicación.
Debido a esto se propone que la tabla de símbolos extienda de un HashMap, para que la aplicación no tenga problemas para la búsqueda de variables cuando las variables almacenadas estén en gran cantidad.

También se propone el uso de entornos, para que al momento de crear una nueva tabla de símbolos, se tenga una tabla de símbolos anterior, y que se puedan crear variables que puedan ser llamadas de la misma manera que en el entorno global sin que exista ningún problema (Parecido a C++).

Ésta última proposición depende de la manera que se quiera manejar el lenguaje.

**Comment by ericknavarro** [comment]
Por favor poner ejemplos claros con código del punto de entornos. ¿Qué no hace el lenguaje actualmente?¿Qué hace mal?¿Qué va a poder hacer con la propuesta?

Sobre el tema de LinkedList ¿Con cuántas variables declaradas la aplicación crashea?¿Realmente es necesaria esta "mejora"?

**Comment by Puac235** [comment]
- En los entornos: Para la explicación del problema utilicé este fragmento de código para el intérprete:

`
numero condicional;
condicional  = 6;
If(condicional > 5){
	imprimir("La condicional " & condicional & " es mayor a 5.");
	numero condicional;
	condicional = 4;
	if(condicional < 5){
		imprimir("La condicional interna " & condicional & " es menor a 5.");
	}
	else
	{
		imprimir("La condicional interna " & condicional & " no es menor a 5.");
	}
}else{
	imprimir("La condicional " & condicional & " es no mayor a 5.");
}
imprimir("El valor de la condicional 'global' es " & condicional);`

El código indica que una condicional se declare en un nuevo entorno (en este caso del If) en donde se le da otro valor y se realiza otra validación. Posteriormente se imprime el valor de la condicional del entorno global, para verificar de que no fue alterada en el proceso.

En la imagen "img2" se encuentra el resultado del intérprete master, en el cual se ve que alteró la variable del entorno global. En la imagen "img3" se puede ver que el problema es que actualmente el intérprete no tiene ninguna validación para verificar que la variable existe; por lo tanto, cuando se declara de nuevo la variable, aparece duplicada, y al momento de cambiar el valor a la variable, siempre va a seleccionar la primera en la tabla de símbolos.

En la imagen "img1" está el resultado del intérprete utilizando entornos, en el cual se puede apreciar que no se alteró la variable del entorno global.

- Con respecto a la LinkedList, he probado con aproximadamente 55 variables declaradas y asignándole un valor y no genera ningún problema; aunque realizando las pruebas de los entornos me di cuenta que la LinkedList no posee una verificación para ver si la variable ya está declarada o no en la tabla de símbolos, por lo que pueden existir duplicados. Al implementar el HashMap no ocurriría esto, debido a que en un HashMap sus claves deben de ser únicas, y al momento de intentar declarar una variable repetida, saltaría un error, el cual se puede controlar mediante un try-catch.

![img1 (2)](https://user-images.githubusercontent.com/53205124/73044265-79bbf400-3e2e-11ea-80e2-0ed2a8933841.png)
![img2 (2)](https://user-images.githubusercontent.com/53205124/73044266-79bbf400-3e2e-11ea-9935-90dd0ef30fe0.png)
![img3 (2)](https://user-images.githubusercontent.com/53205124/73044267-7a548a80-3e2e-11ea-8e80-b9ec27f292a0.png)

**Comment by ericknavarro** [comment]
Buenas tardes @Puac235, 
Por favor proceder con la creación del pull request correspondiente con los cambios propuestos.
Saludos cordiales.
