### ISSUE TITLE
Agregar instruccion Else If

### ISSUE THREAD

**Issue by bchacon45** [ericknavarro/InterpreteSencilloWindows#13]
Propongo agregar la instrucción Else If para aumentar la versatilidad en esta sección de instrucciones "If, If-else". 

Bryan Eduardo Chacón López - 201504290

**Comment by ericknavarro** [comment]
Pull request asociado: https://github.com/ericknavarro/InterpreteSencilloWindows/pull/14

**Comment by rjanixz** [comment]
@bchacon45 buen trabajo. Mandame un correo con tus datos: carnet, nombre, usuario de github, repositorio, sección, número de issue, y número de pull request para control de tu nota.
