### ISSUE TITLE
Agregar operadores lógicos

### ISSUE THREAD

**Issue by sergio23234** [ericknavarro/InterpreteSencilloWindows#5]
Me gustaría proponer una idea para el proyecto, esta seria de agregar operadores lógicos para así poder realizar varias operaciones de comparación simultaneas. 
carnet: 201213282.
nombre: Sergio Fernando De los Rios.

**Comment by ericknavarro** [comment]
Por favor indicar qué operadores lógicos se van a agregar puntualmente.

**Comment by ericknavarro** [comment]
Buenas tardes @sergio23234 , por favor trabajar en el pull request con los cambios propuestos.

Saludos cordiales.
