### ISSUE TITLE
Agregar declaración y asignación en la misma línea

### ISSUE THREAD

**Issue by desog** [ericknavarro/InterpreteSencilloWindows#6]
Agregar el manejo de asignación de valores a las variables en la misma línea que se declaran.
Ejemplo:
//Se declara la variable a, de tipo numero y valor 100.
numero a = 100;

**Comment by ericknavarro** [comment]
Buenas tardes @desog , por favor crear el pull request con los cambios correspondientes.

Saludos cordiales.
