### ISSUE TITLE
Mejora Para el proyecto - Operador Incremento y Decremento

### ISSUE THREAD

**Issue by BrunoCoronado** [ericknavarro/InterpreteSencilloWindows#7]
Se propone la implementación de los operadores incremento (++) y decremento (--) para facilitar la legibilidad en el archivo de entrada.

Ejemplo de implentacion basado en el archivo de entrada propuesto para las tablas del 1 al 5:

mientras(a<4+c){ 
 //a=a+1; <------utilizamos operador incremento en su lugar.
 a++;
 numero b;
 b=0;
 mientras(b<4+c){
//  b=b+1; <------utilizamos operador incremento en su lugar.
  b++;
  imprimir(a & " * " & b & " = " & a * b);
 }
 imprimir("----------------");
}

**Comment by rjanixz** [comment]
Excelente propuesta, link del pr: https://github.com/ericknavarro/InterpreteSencilloWindows/pull/9

**Comment by ericknavarro** [comment]
Muchas gracias por tu aporte Bruno, cierro el issue pues tu pull request hay sido aprobado y confirmado.

**Comment by ericknavarro** [comment]
Muchas gracias por tu aporte Bruno, cierro el issue pues tu pull request hay sido aprobado y confirmado.
